/* parser generated by jison 0.4.18 */
/*
  Returns a Parser object of the following structure:

  Parser: {
    yy: {}
  }

  Parser.prototype: {
    yy: {},
    trace: function(),
    symbols_: {associative list: name ==> number},
    terminals_: {associative list: number ==> name},
    productions_: [...],
    performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate, $$, _$),
    table: [...],
    defaultActions: {...},
    parseError: function(str, hash),
    parse: function(input),

    lexer: {
        EOF: 1,
        parseError: function(str, hash),
        setInput: function(input),
        input: function(),
        unput: function(str),
        more: function(),
        less: function(n),
        pastInput: function(),
        upcomingInput: function(),
        showPosition: function(),
        test_match: function(regex_match_array, rule_index),
        next: function(),
        lex: function(),
        begin: function(condition),
        popState: function(),
        _currentRules: function(),
        topState: function(),
        pushState: function(condition),

        options: {
            ranges: boolean           (optional: true ==> token location info will include a .range[] member)
            flex: boolean             (optional: true ==> flex-like lexing behaviour where the rules are tested exhaustively to find the longest match)
            backtrack_lexer: boolean  (optional: true ==> lexer regexes are tested in order and for each matching regex the action code is invoked; the lexer terminates the scan when a token is returned by the action code)
        },

        performAction: function(yy, yy_, $avoiding_name_collisions, YY_START),
        rules: [...],
        conditions: {associative list: name ==> set},
    }
  }


  token location info (@$, _$, etc.): {
    first_line: n,
    last_line: n,
    first_column: n,
    last_column: n,
    range: [start_number, end_number]       (where the numbers are indexes into the input string, regular zero-based)
  }


  the parseError function receives a 'hash' object with these members for lexer and parser errors: {
    text:        (matched text)
    token:       (the produced terminal token, if any)
    line:        (yylineno)
  }
  while parser (grammar) errors will also provide these members, i.e. parser errors deliver a superset of attributes: {
    loc:         (yylloc)
    expected:    (string describing the set of expected tokens)
    recoverable: (boolean: TRUE when the parser has a error recovery rule available for this particular error)
  }
*/
var asl_write_ascii = (function(){
var o=function(k,v,o,l){for(o=o||{},l=k.length;l--;o[k[l]]=v);return o},$V0=[1,3],$V1=[1,5],$V2=[1,11],$V3=[5,7,8],$V4=[1,16],$V5=[1,17],$V6=[1,18],$V7=[1,19],$V8=[1,20],$V9=[1,21],$Va=[1,33];
var parser = {trace: function trace () { },
yy: {},
symbols_: {"error":2,"Document":3,"GroupList":4,"EOF":5,"Group":6,"(":7,")":8,"Grapheme":9,"[":10,"Connector":11,"]":12,"Iden":13,"Diacritic":14,",":15,"Arrow":16,"IDEN":17,"CARET":18,"AT_SIGN":19,"TWIDDLE":20,"QUOTE":21,"PIPE":22,"UNDERSCORE":23,"VerticalArrow":24,"HorizontalArrow":25,"DASH":26,"DOTS":27,"BANG":28,"GT":29,"$accept":0,"$end":1},
terminals_: {2:"error",5:"EOF",7:"(",8:")",10:"[",12:"]",15:",",17:"IDEN",18:"CARET",19:"AT_SIGN",20:"TWIDDLE",21:"QUOTE",22:"PIPE",23:"UNDERSCORE",26:"DASH",27:"DOTS",28:"BANG",29:"GT"},
productions_: [0,[3,1],[4,1],[4,2],[6,2],[6,3],[6,3],[6,9],[9,1],[9,2],[9,3],[9,2],[11,1],[11,3],[13,1],[14,1],[14,1],[14,1],[14,1],[14,1],[14,1],[16,1],[16,1],[24,2],[25,2],[25,2],[25,3]],
performAction: function anonymous(yytext, yyleng, yylineno, yy, yystate /* action[1] */, $$ /* vstack */, _$ /* lstack */) {
/* this == yyval */

var $0 = $$.length - 1;
switch (yystate) {
case 1:
 window.rootNode = $$[$0]; this.$ = $$[$0]; 
break;
case 2:
 console.log('C'); this.$ = new GroupList(); 
break;
case 3:
 console.log('D', $$[$0], $$[$0-1]); this.$ = $$[$0].push($$[$0-1]); 
break;
case 4:
 this.$ = new Group(null, null, null); 
break;
case 5:
 this.$ = $$[$0-1]; 
break;
case 6:
 this.$ = new Group($$[$0-1], null, null); 
break;
case 7:
 this.$ = new Group($$[$0-7], $$[$0-4], $$[$0-1]); 
break;
case 8:
 this.$ = new Grapheme($$[$0]); 
break;
case 9:
 this.$ = new Grapheme($$[$0], $$[$0-1]); 
break;
case 10:
 this.$ = new Grapheme($$[$0-1], $$[$0-2], $$[$0]); 
break;
case 11:
 this.$ = new Grapheme($$[$0-1], null, $$[$0]); 
break;
case 12:
 this.$ = new Connector($$[$0], new NullArrow()); 
break;
case 13:
 this.$ = new Connector($$[$0-2], $$[$0]); 
break;
case 14:
 this.$ = new Iden($$[$0]); 
break;
case 15: case 16: case 17: case 18: case 19: case 20:
 this.$ = new Diacritic($$[$0]); 
break;
case 21: case 22:
 this.$ = $$[$0]; 
break;
case 23:
 this.$ = $$[$0].setVertical(); 
break;
case 24:
 this.$ = new Arrow(true, false, false, $$[$0].length); 
break;
case 25:
 this.$ = new Arrow(true, true, false, 0); 
break;
case 26:
 this.$ = new Arrow(true, false, true, $$[$0].length); 
break;
}
},
table: [{3:1,4:2,5:$V0,6:4,7:$V1},{1:[3]},{1:[2,1]},{1:[2,2]},{4:6,5:$V0,6:4,7:$V1},{6:8,7:$V1,8:[1,7],9:9,13:10,17:$V2},{1:[2,3]},o($V3,[2,4]),{8:[1,12]},{8:[1,13]},{8:[2,8],13:14,14:15,17:$V2,18:$V4,19:$V5,20:$V6,21:$V7,22:$V8,23:$V9},o([8,12,15,17,18,19,20,21,22,23],[2,14]),o($V3,[2,5],{10:[1,22]}),o($V3,[2,6]),{8:[2,9],14:23,18:$V4,19:$V5,20:$V6,21:$V7,22:$V8,23:$V9},{8:[2,11]},{8:[2,15]},{8:[2,16]},{8:[2,17]},{8:[2,18]},{8:[2,19]},{8:[2,20]},{11:24,13:25,17:$V2},{8:[2,10]},{12:[1,26]},{12:[2,12],15:[1,27]},{7:[1,28]},{16:29,22:[1,32],24:30,25:31,26:$Va},{6:34,7:$V1},{12:[2,13]},{12:[2,21]},{12:[2,22]},{25:35,26:$Va},{27:[1,36],28:[1,37],29:[1,38]},{8:[1,39]},{12:[2,23]},{12:[2,24]},{12:[2,25]},{27:[1,40]},o($V3,[2,7]),{12:[2,26]}],
defaultActions: {2:[2,1],3:[2,2],6:[2,3],15:[2,11],16:[2,15],17:[2,16],18:[2,17],19:[2,18],20:[2,19],21:[2,20],23:[2,10],29:[2,13],30:[2,21],31:[2,22],35:[2,23],36:[2,24],37:[2,25],40:[2,26]},
parseError: function parseError (str, hash) {
    if (hash.recoverable) {
        this.trace(str);
    } else {
        var error = new Error(str);
        error.hash = hash;
        throw error;
    }
},
parse: function parse(input) {
    var self = this, stack = [0], tstack = [], vstack = [null], lstack = [], table = this.table, yytext = '', yylineno = 0, yyleng = 0, recovering = 0, TERROR = 2, EOF = 1;
    var args = lstack.slice.call(arguments, 1);
    var lexer = Object.create(this.lexer);
    var sharedState = { yy: {} };
    for (var k in this.yy) {
        if (Object.prototype.hasOwnProperty.call(this.yy, k)) {
            sharedState.yy[k] = this.yy[k];
        }
    }
    lexer.setInput(input, sharedState.yy);
    sharedState.yy.lexer = lexer;
    sharedState.yy.parser = this;
    if (typeof lexer.yylloc == 'undefined') {
        lexer.yylloc = {};
    }
    var yyloc = lexer.yylloc;
    lstack.push(yyloc);
    var ranges = lexer.options && lexer.options.ranges;
    if (typeof sharedState.yy.parseError === 'function') {
        this.parseError = sharedState.yy.parseError;
    } else {
        this.parseError = Object.getPrototypeOf(this).parseError;
    }
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        var lex = function () {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        };
    var symbol, preErrorSymbol, state, action, a, r, yyval = {}, p, len, newState, expected;
    while (true) {
        state = stack[stack.length - 1];
        if (this.defaultActions[state]) {
            action = this.defaultActions[state];
        } else {
            if (symbol === null || typeof symbol == 'undefined') {
                symbol = lex();
            }
            action = table[state] && table[state][symbol];
        }
                    if (typeof action === 'undefined' || !action.length || !action[0]) {
                var errStr = '';
                expected = [];
                for (p in table[state]) {
                    if (this.terminals_[p] && p > TERROR) {
                        expected.push('\'' + this.terminals_[p] + '\'');
                    }
                }
                if (lexer.showPosition) {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ':\n' + lexer.showPosition() + '\nExpecting ' + expected.join(', ') + ', got \'' + (this.terminals_[symbol] || symbol) + '\'';
                } else {
                    errStr = 'Parse error on line ' + (yylineno + 1) + ': Unexpected ' + (symbol == EOF ? 'end of input' : '\'' + (this.terminals_[symbol] || symbol) + '\'');
                }
                this.parseError(errStr, {
                    text: lexer.match,
                    token: this.terminals_[symbol] || symbol,
                    line: lexer.yylineno,
                    loc: yyloc,
                    expected: expected
                });
            }
        if (action[0] instanceof Array && action.length > 1) {
            throw new Error('Parse Error: multiple actions possible at state: ' + state + ', token: ' + symbol);
        }
        switch (action[0]) {
        case 1:
            stack.push(symbol);
            vstack.push(lexer.yytext);
            lstack.push(lexer.yylloc);
            stack.push(action[1]);
            symbol = null;
            if (!preErrorSymbol) {
                yyleng = lexer.yyleng;
                yytext = lexer.yytext;
                yylineno = lexer.yylineno;
                yyloc = lexer.yylloc;
                if (recovering > 0) {
                    recovering--;
                }
            } else {
                symbol = preErrorSymbol;
                preErrorSymbol = null;
            }
            break;
        case 2:
            len = this.productions_[action[1]][1];
            yyval.$ = vstack[vstack.length - len];
            yyval._$ = {
                first_line: lstack[lstack.length - (len || 1)].first_line,
                last_line: lstack[lstack.length - 1].last_line,
                first_column: lstack[lstack.length - (len || 1)].first_column,
                last_column: lstack[lstack.length - 1].last_column
            };
            if (ranges) {
                yyval._$.range = [
                    lstack[lstack.length - (len || 1)].range[0],
                    lstack[lstack.length - 1].range[1]
                ];
            }
            r = this.performAction.apply(yyval, [
                yytext,
                yyleng,
                yylineno,
                sharedState.yy,
                action[1],
                vstack,
                lstack
            ].concat(args));
            if (typeof r !== 'undefined') {
                return r;
            }
            if (len) {
                stack = stack.slice(0, -1 * len * 2);
                vstack = vstack.slice(0, -1 * len);
                lstack = lstack.slice(0, -1 * len);
            }
            stack.push(this.productions_[action[1]][0]);
            vstack.push(yyval.$);
            lstack.push(yyval._$);
            newState = table[stack[stack.length - 2]][stack[stack.length - 1]];
            stack.push(newState);
            break;
        case 3:
            return true;
        }
    }
    return true;
}};

window.rootNode = null;

let vars = {
    '_font' : '../font',
    '_default-hand': 'R'
};

class Node {
    constructor() { 
        if (this.constructor == Node) {
            throw new Error("Abstract classes can't be instantiated.");
        }
    }
    debugTreeString() { return this._debugTreeString('', '', true, true); }
    _debugTreeString(prefix, arc, last, root) { throw new Error("Method '_debugTreeString()' must be implemented."); };
    eval() { throw new Error("Method 'eval()' must be implemented."); };
}

class GroupList extends Node {
    constructor(firstGroup=null) {
        super();
        this.groups = firstGroup === null ? [] : [firstGroup];
    }

    push(group) {
        this.groups.push(group);
        return this;
    }

    _debugTreeString(prefix, arc, last, root) {
        let s = `${prefix}${arc}GroupList\n`;
        if(this.groups.length == 0) return s;

        for(let i = this.groups.length-1; i >= 0 ; i--) {
            let lastGroup = i == 0;
            let indent =  (root ? '' : (last ? '         ' : ' |       '));
            let newArc = !lastGroup ? " ├───────:" : " └───────:";
            let nl = !lastGroup ? "\n" : "";
            s += `${this.groups[i]._debugTreeString(prefix + indent, newArc, lastGroup, false)}${nl}`;
        }

        return s;
    }

    eval() {
        return this.groups.map((_,i,gs) => gs[gs.length-i-1].eval());
    }
}

class Group extends Node {
    constructor(head, connector = null, tail = null) {
        super();
        this.head = head;
        this.connector = connector;
        this.tail = tail;
    }

    _debugTreeString(prefix, arc, last, root) {
        let s = `${prefix}${arc}Group\n`;
        if(!this.head) return s;

        let indent =  (root ? '' : (last ? '         ' : ' │       '));
        let newArc = this.tail ? " ├─head: " : " └─head: ";
        let nl = this.tail ? "\n" : "";
        s += `${this.head._debugTreeString(prefix + indent, newArc, !this.tail, false)}${nl}`;

        if (this.connector) {
            s += `${this.connector._debugTreeString(prefix + indent, " ├─conn: ", !this.tail, false)}\n`;
        }

        if (this.tail) {
            s += this.tail._debugTreeString(prefix + indent, " └─tail: ", true, false);
        }

        return s;
    }

    eval() {
        return this.head.eval();
    }
}

class Grapheme extends Node {
    constructor(digit, handedness = null, diacritic = null) {
        super();
        this.digit = digit;
        this.handedness = handedness;
        this.diacritic = diacritic;
    }

    _debugTreeString(prefix, arc, last, root) {
        let digitStr = this.digit._debugTreeString('','');
        let handStr = this.handedness ? this.handedness._debugTreeString('','') : '<default hand>';
        if(this.diacritic) {
            let diacriticStr = this.diacritic._debugTreeString();
            return `${prefix}${arc}Grapheme{${digitStr}, ${handStr}, ${diacriticStr}}`;
        }
        return `${prefix}${arc}Grapheme{${digitStr}, ${handStr}}`;
    }

    eval() {
        let digitImg = this.digit.asImg();
        let isRight;
        if(this.handedness) {
            isRight = this.handedness.asHand() == "R";
        } else if(vars['_default-hand'] == 'R') {
            isRight = true;
        } else if(vars['_default-hand'] == 'L') {
            isRight = false;
        } else {
            throw new Error(`_default-hand must be set to L or R, not "${vars['_default-hand']}"`);
        }

        if(!isRight) {
            digitImg.classList.add('_flip');
        }

        return digitImg;
    }
}

const digits = ["0-num","0-flat","1-num","1-claw","1-d","1-i","2-num","2-bend","2-claw","2-close","2-cross","3-num","3-claw","3-close","3-flat","3-k","4-num","4-close","4-claw","5-num","5-close","5-claw","5-half","5-bend","5-c","6-num","6-claw","6-inverse","7-num","7-8","8-num","8-inverse","8-open","9-num","10-num","10-a","10-s","10-t","20-num","1-thumb","20-claw","20-g"];
class Iden extends Node {
    constructor(val) {
        super();
        this.val = val;
    }

    _debugTreeString(prefix, arc, last, root) {
        return `${prefix}${arc}Iden{${this.val}}`;
    }

    asImg() {
        if(digits.includes(this.val)) {
            let digitImg = document.createElement('img');
            digitImg.src = `${vars['_font']}/hand-shapes/${this.val}.svg`;
            return digitImg;
        }
        throw new Error(`Unknown digit name: "${this.val}"`);
    }

    asHand() {
        let upVal = this.val.toUpperCase();
        if(upVal == 'R' || upVal == 'L') return upVal;
        throw new Error(`"${this.val}" is not a valid hand name, must be L or R`);
    }

    eval() {}
}

class Diacritic extends Node {
    constructor(type) {
        super();
        this.type = type;
    }

    _debugTreeString(prefix, arc, last, root) {
        return `Diacritic{${this.type}}`;
    }

    eval() { };
}

class Connector extends Node {
    constructor(iden, arrow = null) {
        super();
        this.iden = iden;
        this.arrow = arrow;
    }

    _debugTreeString(prefix, arc, last, root) {
        return `${prefix}${arc}[${this.iden._debugTreeString('','')}, ${this.arrow._debugTreeString()}]`;
    }

    eval() { };
}

class NullArrow extends Node {
    constructor(){ super(); }
    _debugTreeString() { return 'Arrow{}'; }
    isNull() { return true; }
}

class Arrow extends NullArrow {
    constructor(horizontal, firm, turn, numEndpoints = 0) {
        super();
        this.horizontal = horizontal;
        this.firm = firm;
        this.turn = turn;
        this.numEndpoints = numEndpoints;
    }

    isNull() { return false; }
    setVertical() { this.horizontal = false; return this; }
    setHorizontal() { this.horizontal = true; return this; }

    _debugTreeString(prefix, arc, last, root) {
        let s = 'Arrow{' + (this.horizontal ? '-' : '|-');
        if(this.firm) {
            return s + '!}';
        }
        if(this.turn) {
            s += '>';
        }
        return s + '.'.repeat(this.numEndpoints) + '}';
    }

    eval() { };
}

/* generated by jison-lex 0.3.4 */
var lexer = (function(){
var lexer = ({

EOF:1,

parseError:function parseError(str, hash) {
        if (this.yy.parser) {
            this.yy.parser.parseError(str, hash);
        } else {
            throw new Error(str);
        }
    },

// resets the lexer, sets new input
setInput:function (input, yy) {
        this.yy = yy || this.yy || {};
        this._input = input;
        this._more = this._backtrack = this.done = false;
        this.yylineno = this.yyleng = 0;
        this.yytext = this.matched = this.match = '';
        this.conditionStack = ['INITIAL'];
        this.yylloc = {
            first_line: 1,
            first_column: 0,
            last_line: 1,
            last_column: 0
        };
        if (this.options.ranges) {
            this.yylloc.range = [0,0];
        }
        this.offset = 0;
        return this;
    },

// consumes and returns one char from the input
input:function () {
        var ch = this._input[0];
        this.yytext += ch;
        this.yyleng++;
        this.offset++;
        this.match += ch;
        this.matched += ch;
        var lines = ch.match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno++;
            this.yylloc.last_line++;
        } else {
            this.yylloc.last_column++;
        }
        if (this.options.ranges) {
            this.yylloc.range[1]++;
        }

        this._input = this._input.slice(1);
        return ch;
    },

// unshifts one char (or a string) into the input
unput:function (ch) {
        var len = ch.length;
        var lines = ch.split(/(?:\r\n?|\n)/g);

        this._input = ch + this._input;
        this.yytext = this.yytext.substr(0, this.yytext.length - len);
        //this.yyleng -= len;
        this.offset -= len;
        var oldLines = this.match.split(/(?:\r\n?|\n)/g);
        this.match = this.match.substr(0, this.match.length - 1);
        this.matched = this.matched.substr(0, this.matched.length - 1);

        if (lines.length - 1) {
            this.yylineno -= lines.length - 1;
        }
        var r = this.yylloc.range;

        this.yylloc = {
            first_line: this.yylloc.first_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.first_column,
            last_column: lines ?
                (lines.length === oldLines.length ? this.yylloc.first_column : 0)
                 + oldLines[oldLines.length - lines.length].length - lines[0].length :
              this.yylloc.first_column - len
        };

        if (this.options.ranges) {
            this.yylloc.range = [r[0], r[0] + this.yyleng - len];
        }
        this.yyleng = this.yytext.length;
        return this;
    },

// When called from action, caches matched text and appends it on next action
more:function () {
        this._more = true;
        return this;
    },

// When called from action, signals the lexer that this rule fails to match the input, so the next matching rule (regex) should be tested instead.
reject:function () {
        if (this.options.backtrack_lexer) {
            this._backtrack = true;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });

        }
        return this;
    },

// retain first n characters of the match
less:function (n) {
        this.unput(this.match.slice(n));
    },

// displays already matched input, i.e. for error messages
pastInput:function () {
        var past = this.matched.substr(0, this.matched.length - this.match.length);
        return (past.length > 20 ? '...':'') + past.substr(-20).replace(/\n/g, "");
    },

// displays upcoming input, i.e. for error messages
upcomingInput:function () {
        var next = this.match;
        if (next.length < 20) {
            next += this._input.substr(0, 20-next.length);
        }
        return (next.substr(0,20) + (next.length > 20 ? '...' : '')).replace(/\n/g, "");
    },

// displays the character position where the lexing error occurred, i.e. for error messages
showPosition:function () {
        var pre = this.pastInput();
        var c = new Array(pre.length + 1).join("-");
        return pre + this.upcomingInput() + "\n" + c + "^";
    },

// test the lexed token: return FALSE when not a match, otherwise return token
test_match:function(match, indexed_rule) {
        var token,
            lines,
            backup;

        if (this.options.backtrack_lexer) {
            // save context
            backup = {
                yylineno: this.yylineno,
                yylloc: {
                    first_line: this.yylloc.first_line,
                    last_line: this.last_line,
                    first_column: this.yylloc.first_column,
                    last_column: this.yylloc.last_column
                },
                yytext: this.yytext,
                match: this.match,
                matches: this.matches,
                matched: this.matched,
                yyleng: this.yyleng,
                offset: this.offset,
                _more: this._more,
                _input: this._input,
                yy: this.yy,
                conditionStack: this.conditionStack.slice(0),
                done: this.done
            };
            if (this.options.ranges) {
                backup.yylloc.range = this.yylloc.range.slice(0);
            }
        }

        lines = match[0].match(/(?:\r\n?|\n).*/g);
        if (lines) {
            this.yylineno += lines.length;
        }
        this.yylloc = {
            first_line: this.yylloc.last_line,
            last_line: this.yylineno + 1,
            first_column: this.yylloc.last_column,
            last_column: lines ?
                         lines[lines.length - 1].length - lines[lines.length - 1].match(/\r?\n?/)[0].length :
                         this.yylloc.last_column + match[0].length
        };
        this.yytext += match[0];
        this.match += match[0];
        this.matches = match;
        this.yyleng = this.yytext.length;
        if (this.options.ranges) {
            this.yylloc.range = [this.offset, this.offset += this.yyleng];
        }
        this._more = false;
        this._backtrack = false;
        this._input = this._input.slice(match[0].length);
        this.matched += match[0];
        token = this.performAction.call(this, this.yy, this, indexed_rule, this.conditionStack[this.conditionStack.length - 1]);
        if (this.done && this._input) {
            this.done = false;
        }
        if (token) {
            return token;
        } else if (this._backtrack) {
            // recover context
            for (var k in backup) {
                this[k] = backup[k];
            }
            return false; // rule action called reject() implying the next rule should be tested instead.
        }
        return false;
    },

// return next match in input
next:function () {
        if (this.done) {
            return this.EOF;
        }
        if (!this._input) {
            this.done = true;
        }

        var token,
            match,
            tempMatch,
            index;
        if (!this._more) {
            this.yytext = '';
            this.match = '';
        }
        var rules = this._currentRules();
        for (var i = 0; i < rules.length; i++) {
            tempMatch = this._input.match(this.rules[rules[i]]);
            if (tempMatch && (!match || tempMatch[0].length > match[0].length)) {
                match = tempMatch;
                index = i;
                if (this.options.backtrack_lexer) {
                    token = this.test_match(tempMatch, rules[i]);
                    if (token !== false) {
                        return token;
                    } else if (this._backtrack) {
                        match = false;
                        continue; // rule action called reject() implying a rule MISmatch.
                    } else {
                        // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
                        return false;
                    }
                } else if (!this.options.flex) {
                    break;
                }
            }
        }
        if (match) {
            token = this.test_match(match, rules[index]);
            if (token !== false) {
                return token;
            }
            // else: this is a lexer rule which consumes input without producing a token (e.g. whitespace)
            return false;
        }
        if (this._input === "") {
            return this.EOF;
        } else {
            return this.parseError('Lexical error on line ' + (this.yylineno + 1) + '. Unrecognized text.\n' + this.showPosition(), {
                text: "",
                token: null,
                line: this.yylineno
            });
        }
    },

// return next match that has a token
lex:function lex () {
        var r = this.next();
        if (r) {
            return r;
        } else {
            return this.lex();
        }
    },

// activates a new lexer condition state (pushes the new lexer condition state onto the condition stack)
begin:function begin (condition) {
        this.conditionStack.push(condition);
    },

// pop the previously active lexer condition state off the condition stack
popState:function popState () {
        var n = this.conditionStack.length - 1;
        if (n > 0) {
            return this.conditionStack.pop();
        } else {
            return this.conditionStack[0];
        }
    },

// produce the lexer rule set which is active for the currently active lexer condition state
_currentRules:function _currentRules () {
        if (this.conditionStack.length && this.conditionStack[this.conditionStack.length - 1]) {
            return this.conditions[this.conditionStack[this.conditionStack.length - 1]].rules;
        } else {
            return this.conditions["INITIAL"].rules;
        }
    },

// return the currently active lexer condition state; when an index argument is provided it produces the N-th previous condition state, if available
topState:function topState (n) {
        n = this.conditionStack.length - 1 - Math.abs(n || 0);
        if (n >= 0) {
            return this.conditionStack[n];
        } else {
            return "INITIAL";
        }
    },

// alias for begin(condition)
pushState:function pushState (condition) {
        this.begin(condition);
    },

// return the number of states currently on the stack
stateStackSize:function stateStackSize() {
        return this.conditionStack.length;
    },
options: {},
performAction: function anonymous(yy,yy_,$avoiding_name_collisions,YY_START) {
var YYSTATE=YY_START;
switch($avoiding_name_collisions) {
case 0:/* skip whitespace */
break;
case 1:return 7;
break;
case 2:return 8;
break;
case 3:return 10;
break;
case 4:return 12;
break;
case 5:return 15;
break;
case 6:return 17;
break;
case 7:return 18;
break;
case 8:return 19;
break;
case 9:return 20;
break;
case 10:return 21;
break;
case 11:return 23;
break;
case 12:return 22;
break;
case 13:return 26;
break;
case 14:return 29;
break;
case 15:return 28;
break;
case 16:return 27;
break;
case 17:return 5;
break;
}
},
rules: [/^(?:\s+)/,/^(?:\()/,/^(?:\))/,/^(?:\[)/,/^(?:\])/,/^(?:,)/,/^(?:[A-Za-z0-9\-]+)/,/^(?:\^)/,/^(?:@)/,/^(?:~)/,/^(?:")/,/^(?:_\b)/,/^(?:\|)/,/^(?:-)/,/^(?:>)/,/^(?:!)/,/^(?:\.+)/,/^(?:$)/],
conditions: {"INITIAL":{"rules":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17],"inclusive":true}}
});
return lexer;
})();
parser.lexer = lexer;
function Parser () {
  this.yy = {};
}
Parser.prototype = parser;parser.Parser = Parser;
return new Parser;
})();


if (typeof require !== 'undefined' && typeof exports !== 'undefined') {
exports.parser = asl_write_ascii;
exports.Parser = asl_write_ascii.Parser;
exports.parse = function () { return asl_write_ascii.parse.apply(asl_write_ascii, arguments); };
exports.main = function commonjsMain (args) {
    if (!args[1]) {
        console.log('Usage: '+args[0]+' FILE');
        process.exit(1);
    }
    var source = require('fs').readFileSync(require('path').normalize(args[1]), "utf8");
    return exports.parser.parse(source);
};
if (typeof module !== 'undefined' && require.main === module) {
  exports.main(process.argv.slice(1));
}
}